export const logError = (error: unknown): void => {
    console.error("An error occurred:", error);
}